# Generated by Django 2.0 on 2021-04-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barter',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='bartertype',
            options={'verbose_name': '换品种类', 'verbose_name_plural': '换品种类'},
        ),
        migrations.AddField(
            model_name='barter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barter', verbose_name='商品图片'),
        ),
        migrations.AddField(
            model_name='barter',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='barter',
            name='want_barter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bartertype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bartertype', verbose_name='商品类型图片'),
        ),
        migrations.AlterField(
            model_name='bartertype',
            name='type_name',
            field=models.CharField(max_length=20, verbose_name='种类名称'),
        ),
    ]
