# Generated by Django 2.0 on 2021-04-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_auto_20210413_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barter',
            old_name='title',
            new_name='name',
        ),
    ]
