# Generated by Django 2.0 on 2021-04-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_auto_20210413_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='where',
            field=models.SmallIntegerField(choices=[(0, '奉贤'), (1, '徐汇')], default=0, verbose_name='所在校区'),
        ),
        migrations.AlterField(
            model_name='barter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barter/%Y%m%d/', verbose_name='商品图片'),
        ),
    ]
