# Generated by Django 2.0 on 2021-06-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0006_application_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
