# Generated by Django 2.0 on 2021-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='is_delete',
            field=models.SmallIntegerField(default=0, verbose_name='帖子状态'),
        ),
    ]
